admin:
  existingSecret: bytebattle-secrets
  userKey: GRAFANA_ADMIN_USER
  passwordKey: GRAFANA_ADMIN_PASSWORD
dashboardsProvider:
  enabled: true
dashboardsConfigMaps:
  default: grafana-dashboards
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
