apiVersion: v1
kind: ConfigMap
metadata:
  name: bytebattle-config
  namespace: bytebattle-devops
  labels:
    app.kubernetes.io/name: bytebattle
data:
  NODE_ENV: production
  PORT: "3000"
  MONGODB_URI: mongodb://mongodb-service:27017/bytebattle
  CORS_ORIGIN: http://bytebattle.local
  RATE_LIMIT_POINTS_PER_MINUTE: "120"
  CODE_EXECUTION_PREFER_LOCAL: "true"
  PISTON_ENDPOINT: http://piston-service:2000/api/v2/execute
