import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { RootState } from '../../store/store';
import { PageContainer, Card, Button } from '../../shared/components';

function Home() {
  const { isAuthenticated } = useSelector((state: RootState) => state.auth);

  return (
    <PageContainer maxWidth="7xl" className="py-12">
      <div className="text-center">
        <h1 className="mb-6 flex justify-center">
          <img
            src="/bytebattle-logo.png"
            alt="Byte Battle"
            className="h-24 sm:h-28 md:h-32 w-auto origin-center"
            style={{ transform: 'rotate(-3deg)' }}
          />
        </h1>
        <p className="text-xl text-gray-600 dark:text-gray-300 mb-8 max-w-2xl mx-auto">
          Real-time code challenge platform. Compete, learn and improve your skills with AI-generated challenges.
        </p>
        <div className="flex justify-center gap-4 flex-wrap">
          {isAuthenticated ? (
            <>
              <Link to="/challenges">
                <Button className="!px-8 !py-3 text-lg">Start coding</Button>
              </Link>
              <Link to="/competitions">
                <Button variant="secondary" className="!px-8 !py-3 text-lg">Join a battle</Button>
              </Link>
            </>
          ) : (
            <>
              <Link to="/register">
                <Button className="!px-8 !py-3 text-lg">Create an account</Button>
              </Link>
              <Link to="/challenges">
                <Button variant="secondary" className="!px-8 !py-3 text-lg">Browse challenges</Button>
              </Link>
            </>
          )}
        </div>
      </div>

      <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8">
        <Card title="Real-time battles">
          <p className="text-gray-500 dark:text-gray-400">
            Face other players in 1v1 or team mode with live code execution and real-time leaderboards.
          </p>
        </Card>
        <Card title="AI-powered challenges">
          <p className="text-gray-500 dark:text-gray-400">
            Get personalized challenges generated by AI based on your level and interests.
          </p>
        </Card>
        <Card title="Progress tracking">
          <p className="text-gray-500 dark:text-gray-400">
            Track your performance with detailed stats, achievements and learning paths.
          </p>
        </Card>
      </div>
    </PageContainer>
  );
}

export default Home;
