import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { RootState } from '../../store/store';

function Home() {
  const { isAuthenticated } = useSelector((state: RootState) => state.auth);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="text-center">
        <h1 className="text-5xl font-bold mb-6 bg-gradient-to-r from-primary-400 to-primary-600 bg-clip-text text-transparent">
          ByteBattle
        </h1>
        <p className="text-xl text-gray-300 mb-8 max-w-2xl mx-auto">
          Real-Time Collaborative Coding Challenge Platform. Compete, learn, and
          improve your programming skills through AI-generated challenges.
        </p>
        <div className="flex justify-center space-x-4">
          {isAuthenticated ? (
            <>
              <Link
                to="/challenges"
                className="bg-primary-600 hover:bg-primary-700 text-white px-8 py-3 rounded-lg text-lg font-semibold"
              >
                Start Coding
              </Link>
              <Link
                to="/competitions"
                className="bg-gray-700 hover:bg-gray-600 text-white px-8 py-3 rounded-lg text-lg font-semibold"
              >
                Join Battle
              </Link>
            </>
          ) : (
            <>
              <Link
                to="/register"
                className="bg-primary-600 hover:bg-primary-700 text-white px-8 py-3 rounded-lg text-lg font-semibold"
              >
                Get Started
              </Link>
              <Link
                to="/challenges"
                className="bg-gray-700 hover:bg-gray-600 text-white px-8 py-3 rounded-lg text-lg font-semibold"
              >
                Browse Challenges
              </Link>
            </>
          )}
        </div>
      </div>

      <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="bg-gray-800 p-6 rounded-lg">
          <h3 className="text-xl font-semibold mb-4">Real-Time Battles</h3>
          <p className="text-gray-400">
            Compete in 1v1 battles or team competitions with real-time code
            execution and live leaderboards.
          </p>
        </div>
        <div className="bg-gray-800 p-6 rounded-lg">
          <h3 className="text-xl font-semibold mb-4">AI-Powered Challenges</h3>
          <p className="text-gray-400">
            Get personalized challenges generated by AI based on your skill level
            and interests.
          </p>
        </div>
        <div className="bg-gray-800 p-6 rounded-lg">
          <h3 className="text-xl font-semibold mb-4">Track Progress</h3>
          <p className="text-gray-400">
            Monitor your performance with detailed statistics, achievements, and
            personalized learning paths.
          </p>
        </div>
      </div>
    </div>
  );
}

export default Home;

